version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "dev"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "dev"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "dev"
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "dev"
