name: build

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Fetch tag name
      id: tag
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Set up QEMU for multiarch build
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_PAT }}
    - name: Build and push containers
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:test
          ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
