name: release


on:
  push:
    branches:
    - main


jobs:

  tag:
    name: Create version tag
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag.outputs.changelog }}
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Bump version and tag
      uses: mathieudutour/github-tag-action@v6.0
      id: tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  containers:
    name: Create containers
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_PAT }}
    - name: Build and push containers
      uses: docker/build-push-action@v2
      env:
        VERSION: ${{ needs.tag.outputs.tag }}
      with:
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ needs.tag.outputs.tag }}
          org.opencontainers.image.revision=${{ github.sha }}

  binaries:
    name: Create binaries
    runs-on: ubuntu-latest
    needs: tag
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
        - goos: windows
          goarch: "386"
        - goos: windows
          goarch: arm
        - goos: windows
          goarch: arm64
        - goos: darwin
          goarch: "386"
        - goos: darwin
          goarch: arm
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.16'
    - name: Build binaries
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        BINARY: ${{ github.event.repository.name }}-${{ needs.tag.outputs.tag }}-${{ matrix.goos }}-${{ matrix.goarch }}
        VERSIONFLAG: -X 'main.Version=${{ needs.tag.outputs.tag }}'
      run: |
        go build -ldflags="${VERSIONFLAG}" -o ${BINARY}
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ${{ github.event.repository.name }}-v*-*-*
        retention-days: 1

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
    - tag
    - binaries
    - containers
    steps:
    - name: Fetch binaries
      uses: actions/download-artifact@v3
      with:
        name: binaries
    - name: Create checksums
      run: |
        sha256sum ${{ github.event.repository.name }}-v*-*-* | tee ${{ github.event.repository.name }}-${{ needs.tag.outputs.tag }}.sha256
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        name: Release ${{ needs.tag.outputs.version }}
        body: |
          Changes in this release:
          ${{ needs.tag.outputs.changelog }}
          Docker image: ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
        files: ${{ github.event.repository.name }}-v*-*-*,${{ github.event.repository.name }}-*.sha256
