name: test


on: pull_request


jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.16'
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      
  containers:
    name: Create containers
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build containers
      uses: docker/build-push-action@v2
      with:
        push: false
        platforms: linux/amd64,linux/arm/v7,linux/arm64

  binaries:
    name: Create binaries
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
        - goos: windows
          goarch: "386"
        - goos: windows
          goarch: arm
        - goos: windows
          goarch: arm64
        - goos: darwin
          goarch: "386"
        - goos: darwin
          goarch: arm
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.16'
    - name: Build binaries
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build